extends SceneTree

## DEMO-RC-G6-02 — 전술 임무 상시 변경과 판정 중 변경의 다음 턴 적용
const Harness := preload("res://tests/harness.gd")
const Setup := preload("res://core/demo_red_cliffs/red_cliffs_demo_setup.gd")
const Mission := preload("res://core/demo_red_cliffs/red_cliffs_fast_craft_mission.gd")
const Battle := preload("res://core/demo_red_cliffs/red_cliffs_turn_battle.gd")

var _pass := 0
var _fail := 0

func _ok(value: bool, label: String) -> void:
	if value: _pass += 1
	else: _fail += 1; print("  x %s" % label)

func _eq(actual, expected, label: String) -> void: _ok(actual == expected, "%s (%s != %s)" % [label, str(actual), str(expected)])
func _init() -> void: call_deferred("_run")

func _run() -> void:
	print("DEMO-RC-G6-02 — 전술 임무 상시 변경과 판정 중 변경의 다음 턴 적용")
	_test_rules_and_reducer()
	_test_battle_immediate_queue_promotion_and_redaction()
	print("PASS %d / FAIL %d" % [_pass, _fail])
	quit(Harness.EXIT_FAIL if _fail > 0 else Harness.EXIT_PASS)

func _setup() -> Dictionary:
	var loaded := Setup.load_default(); _ok(loaded.ok, "default setup loads"); return loaded.setup.duplicate(true)

func _test_rules_and_reducer() -> void:
	var resolver = Mission.new(); _ok(resolver.initialize(_setup()).ok, "mission resolver initializes")
	var catalog: Dictionary = resolver.catalog()
	_eq(catalog.equipment_allowlists["FAST-EQ-INTERCEPT"], ["intercept", "escort"], "intercept equipment allowlist")
	_eq(catalog.equipment_allowlists["FAST-EQ-TORPEDO"], ["torpedo", "strike"], "torpedo equipment allowlist")
	_eq(catalog.equipment_allowlists["FAST-EQ-RECON"], ["recon", "liaison"], "recon equipment allowlist")
	_eq(catalog.equipment_allowlists["FAST-EQ-RESCUE"], ["rescue", "liaison"], "rescue equipment allowlist")
	_eq(catalog.result_pending, ["non_rescue_mission_effect"], "only non-rescue tactical mission effects stay pending after G6-05")
	var state: Dictionary = resolver.initial_state(); var original := JSON.stringify(state)
	_eq(resolver.ai_mission(state, "RC-LIU-FC-01", 1).mission_id, "recon", "AI turn-one policy deterministically selects first allowlisted mission")
	_eq(resolver.ai_mission(state, "RC-LIU-FC-01", 2).mission_id, "liaison", "AI turn-two policy deterministically selects second allowlisted mission")
	_ok(not resolver.ai_mission(state, "UNKNOWN", 2).ok, "AI uses the same squadron eligibility boundary")
	_eq(state.active["RC-LIU-FC-01"].equipment_id, "FAST-EQ-RECON", "equipment is immutable setup input")
	_eq(state.active["RC-LIU-FC-01"].mission_id, "recon", "equipment default initializes active mission")
	var invalid := resolver.request(state, "RC-LIU-FC-01", "torpedo", 1, "immediate")
	_ok(not invalid.ok, "unsupported mission is rejected")
	_eq(JSON.stringify(state), original, "invalid reducer request is atomic")
	var changed: Dictionary = resolver.request(state, "RC-LIU-FC-01", "liaison", 1, "immediate")
	_ok(changed.ok and changed.application == "immediate", "allowlisted mission appears in current draft immediately")
	_eq(changed.state.active["RC-LIU-FC-01"].mission_id, "recon", "draft does not mutate authoritative active mission")
	_eq(changed.state.active["RC-LIU-FC-01"].equipment_id, "FAST-EQ-RECON", "mission draft cannot replace equipment")
	_eq(JSON.stringify(state), original, "valid reducer also deep-copies caller state")
	_ok(not resolver.request(changed.state, "RC-LIU-FC-01", "liaison", 1, "immediate").ok, "draft duplicate is rejected")
	var committed: Dictionary = resolver.commit_draft(changed.state, "liu_bei", [{"squadron_id":"RC-LIU-FC-01", "mission_id":"liaison"}], 1)
	_eq(committed.state.active["RC-LIU-FC-01"].mission_id, "liaison", "submit atomically commits active mission")
	_eq(committed.state.current_turn_draft, {}, "submit consumes current draft")
	var queued: Dictionary = resolver.request(committed.state, "RC-LIU-FC-01", "recon", 1, "next_turn_queue")
	_ok(queued.ok and queued.event.status == "queued", "late request is queued")
	_ok(not resolver.request(queued.state, "RC-LIU-FC-01", "liaison", 1, "next_turn_queue").ok, "second queue request is rejected")
	var promoted: Dictionary = resolver.promote(queued.state, 2)
	_eq(promoted.state.active["RC-LIU-FC-01"].mission_id, "recon", "queued mission promotes once")
	_eq(promoted.state.next_turn_queue, {}, "promotion consumes queue")
	_eq(resolver.promote(promoted.state, 2).events, [], "same turn cannot promote twice")

func _test_battle_immediate_queue_promotion_and_redaction() -> void:
	var battle = Battle.new(); _ok(battle.initialize(_setup()).ok, "battle initializes")
	var before := battle.digest(); var invalid := battle.set_fast_craft_mission("liu_bei", "RC-LIU-FC-01", "torpedo")
	_ok(not invalid.ok, "battle rejects equipment-ineligible mission")
	_eq(battle.digest(), before, "invalid battle request is atomic")
	var immediate: Dictionary = battle.set_fast_craft_mission("liu_bei", "RC-LIU-FC-01", "liaison")
	_ok(immediate.ok and immediate.application == "immediate" and immediate.event.status == "immediate", "Liu command request applies to current draft")
	_eq(battle.command_draft().fast_craft_mission_orders["RC-LIU-FC-01"].mission_id, "liaison", "current draft records mission intent")
	_eq(battle.viewer_fast_craft_missions("liu_bei").statuses[0].mission_id, "recon", "active mission remains unchanged before submit")
	_eq(battle.viewer_fast_craft_missions("liu_bei").statuses[0].display_mission_id, "liaison", "UI receipt reflects current draft immediately")
	_eq(battle.viewer_fast_craft_missions("liu_bei").statuses[0].equipment_id, "FAST-EQ-RECON", "live equipment remains immutable")
	_ok(battle.viewer_fast_craft_missions("liu_bei").statuses[0].can_change, "command draft remains reselectable")
	_ok(battle.viewer_fast_craft_missions("cao_cao").statuses.is_empty(), "enemy cannot inspect Liu mission status")
	var duplicate_digest := battle.digest(); _ok(not battle.set_fast_craft_mission("liu_bei", "RC-LIU-FC-01", "liaison").ok, "exact duplicate current-draft request rejected")
	_eq(battle.digest(), duplicate_digest, "exact duplicate rejection is atomic")
	_ok(battle.set_fast_craft_mission("liu_bei", "RC-LIU-FC-01", "recon").ok, "reselecting active mission cancels the pending draft")
	_eq(battle.command_draft().fast_craft_mission_orders, {}, "last valid active choice clears mission draft")
	_ok(battle.set_fast_craft_mission("liu_bei", "RC-LIU-FC-01", "liaison").ok, "last valid alternate choice wins")
	_ok(not battle.submit_liu_orders([]).ok, "invalid command submission is rejected")
	_eq(battle.viewer_fast_craft_missions("liu_bei").statuses[0].mission_id, "recon", "invalid submit cannot commit active mission")
	_eq(battle.viewer_fast_craft_missions("liu_bei").statuses[0].display_mission_id, "liaison", "invalid submit preserves the editable mission draft")
	_ok(battle.submit_command_draft().ok, "Liu draft submits")
	_eq(battle.viewer_fast_craft_missions("liu_bei").statuses[0].mission_id, "liaison", "successful submit commits active mission")
	_ok(battle.submit_sun_control_choice("ai").ok, "AI route reaches resolution")
	var cross_digest := battle.digest(); _ok(not battle.set_fast_craft_mission("cao_cao", "RC-LIU-FC-01", "recon").ok, "cross-faction late mutation is rejected")
	_eq(battle.digest(), cross_digest, "cross-faction late mutation rejection is atomic")
	var queued: Dictionary = battle.set_fast_craft_mission("liu_bei", "RC-LIU-FC-01", "recon")
	_ok(queued.ok and queued.application == "next_turn_queue", "resolution-phase request queues for next turn")
	_eq(battle.viewer_fast_craft_missions("liu_bei").statuses[0].mission_id, "liaison", "queue does not mutate active mission")
	_eq(battle.viewer_fast_craft_missions("liu_bei").queued[0].effective_turn, 2, "queue advertises next turn")
	_ok(battle.viewer_fast_craft_missions("liu_bei").statuses[0].can_cancel, "queued request publishes cancel capability")
	var queue_digest := battle.digest(); _ok(not battle.set_fast_craft_mission("liu_bei", "RC-LIU-FC-01", "recon").ok, "duplicate late request rejected")
	_eq(battle.digest(), queue_digest, "duplicate late request is atomic")
	_ok(not battle.cancel_queued_fast_craft_mission("cao_cao", "RC-LIU-FC-01").ok, "cross-faction queue cancellation is rejected")
	_eq(battle.digest(), queue_digest, "cross-faction cancellation rejection is atomic")
	var cancelled: Dictionary = battle.cancel_queued_fast_craft_mission("liu_bei", "RC-LIU-FC-01")
	_ok(cancelled.ok and cancelled.event.status == "cancelled", "late queue can be cancelled without touching active mission")
	_ok(battle.set_fast_craft_mission("liu_bei", "RC-LIU-FC-01", "recon").ok, "cancelled slot accepts one replacement queue")
	var receipt: Dictionary = battle.resolve_turn(); _ok(receipt.ok, "turn resolves without mission effects")
	_ok(receipt.fast_craft_mission_events.any(func(row): return String(row.status) == "queued"), "raw receipt carries queued status")
	_ok(receipt.fast_craft_mission_events.all(func(row): return not row.has("success") and not row.has("damage") and not row.has("fuel")), "receipt fabricates no G6-03+ result")
	_ok(battle.continue_turn().ok, "next command turn begins")
	var viewer: Dictionary = battle.viewer_fast_craft_missions("liu_bei")
	_eq(viewer.statuses[0].mission_id, "recon", "queue promotes before next command draft")
	_eq(viewer.statuses[0].source, "next_turn_promotion", "promotion source is explicit")
	_eq(viewer.queued, [], "promoted queue is consumed")
	_eq(viewer.events[-1].status, "promoted", "viewer latest event preserves actual append order after promotion")
	_ok(int(viewer.events[-1].serial) > int(viewer.events[-2].serial), "promotion has a monotonic event serial")
	_eq(battle.command_draft().fast_craft_mission_orders, {}, "promotion is not replayed as a new request")
	_eq(JSON.stringify(battle.snapshot()).contains("Vector2"), false, "mission state remains save-serializable primitives")
	_test_turn_twenty_queue_guard()

func _test_turn_twenty_queue_guard() -> void:
	var battle = Battle.new(); _ok(battle.initialize(_setup()).ok, "turn-limit fixture initializes")
	for expected_turn in range(1, 20):
		_ok(battle.submit_command_draft().ok, "turn %d Liu submits" % expected_turn)
		_ok(battle.submit_sun_control_choice("ai").ok, "turn %d AI prepares" % expected_turn)
		_ok(battle.resolve_turn().ok, "turn %d resolves" % expected_turn)
		_ok(battle.continue_turn().ok, "turn %d continues" % expected_turn)
	_ok(battle.submit_command_draft().ok and battle.submit_sun_control_choice("ai").ok, "turn 20 reaches resolution")
	var status: Dictionary = battle.viewer_fast_craft_missions("liu_bei").statuses[0]
	_eq(status.application, "read_only", "turn 20 has no impossible next-turn queue capability")
	_eq(status.change_reason, "turn_limit_no_next_turn", "turn-limit denial reason is explicit")
	var digest := battle.digest(); _ok(not battle.set_fast_craft_mission("liu_bei", "RC-LIU-FC-01", "liaison").ok, "turn 20 late queue is rejected")
	_eq(battle.digest(), digest, "turn 20 rejection is atomic")
